### ISSUE TITLE
gmail marking forwardemail as spam

### ISSUE THREAD

**Issue by bradlosh** [niftylettuce/forward-email#10] opened 2018-03-29 13:24 UTC
Hi and thankyou for a great product.  I setup my account yesterday to forward to my gmail account.  today, these emails are being returned as spam.  I use iwantmyname for dns... any suggestions?

**Comment by aliblackwell** [comment] 2018-04-09 16:25
I'm getting this issue as well. I have updated the SPF records as per the instructions. 

Below are the headers for an email sent from a gmail account to ali@crypticalstudios.com with DNS configuration set to forward to ali@protonmail.com. Have the forwardemail.net servers been added to some sort of spam database? Do we need to run the software ourselves?

Many thanks

```
Return-Path: <aliblackwell@gmail.com>
X-Original-To: aliblackwell@protonmail.com
Delivered-To: aliblackwell@protonmail.com
Received: from mx1.forwardemail.net (mx1.forwardemail.net [192.81.219.215]) (using
 TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)) (No client certificate
 requested) by mail7i.protonmail.ch (Postfix) with ESMTPS id 044DE582 for
 <aliblackwell@protonmail.com>; Mon,
  9 Apr 2018 12:04:52 -0400 (EDT)
Received: by mail-oi0-f52.google.com with SMTP id f63-v6so8134198oic.4 for
 <ali@crypticalstudios.com>; Mon, 09 Apr 2018 09:04:45 -0700 (PDT)
Authentication-Results: mail7i.protonmail.ch; dmarc=fail (p=none dis=none)
 header.from=gmail.com
Authentication-Results: mail7i.protonmail.ch; spf=fail
 smtp.mailfrom=aliblackwell@gmail.com
Authentication-Results: mail7i.protonmail.ch; dkim=pass (1024-bit key)
 header.d=forwardemail.net header.i=@forwardemail.net header.b="BD1GSItg"
Dkim-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=forwardemail.net; q=dns/txt;
 s=default; bh=G0PqCbWxmuucDuhQAcXSQj09fmYFtX1ioDMAvBWlxLI=;
 h=from:subject:date:message-id:to:mime-version:content-type;
 b=BD1GSItg8Vm6ydjDC3MKpIBL8mOaJYO4k6miIJ1wHhOPVwkv432pHr74JWP4ohmgqmBRbxg0A
 LT5qFEV2JNpAIItGEYHRBKCd3XKL5y0JNf86itgbaWpY1oh8Xi0Sy/ghThBtupvcTaOMzuKyw8V
 TG/VnGoSys9jO06LMAAU3WQ=
Content-Type: text/html
From: Alasdair Blackwell <aliblackwell@gmail.com>
To: ali@crypticalstudios.com
Subject: Test
Date: Mon, 09 Apr 2018 15:57:50 +0000
Message-Id: <205c294e-1b9e-92a4-2bba-2e2da082cbf6@gmail.com>
Mime-Version: 1.0
X-Spam-Flag: YES
X-Spam-Status: Yes, score=5.6 required=4.0 tests=BAYES_50,DKIM_ADSP_CUSTOM_MED,
 DKIM_SIGNED,DKIM_VALID,FREEMAIL_FROM,HTML_MESSAGE,NML_ADSP_CUSTOM_MED, SPF_SOFTFAIL
 autolearn=no autolearn_force=no version=3.4.0
X-Spam-Report: *
  0.0 FREEMAIL_FROM Sender email is commonly abused enduser mail provider *
      (aliblackwell[at]gmail.com) *
  0.0 DKIM_ADSP_CUSTOM_MED No valid author signature, adsp_override is *
      CUSTOM_MED *
  0.7 SPF_SOFTFAIL SPF: sender does not match SPF record (softfail) *
  0.0 HTML_MESSAGE BODY: HTML included in message *
  4.0 BAYES_50 BODY: Bayes spam probability is 40 to 60% *
      [score: 0.4348] *
  0.1 DKIM_SIGNED Message has a DKIM or DK signature, not necessarily *
      valid * -0.1 DKIM_VALID Message has at least one valid DKIM or DK signature *
  0.9 NML_ADSP_CUSTOM_MED ADSP custom_med hit, and not from a mailing list
X-Spam-Level: *****
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on maili.protonmail.ch
X-Pm-Origin: external
X-Pm-Content-Encryption: on-delivery
X-Pm-Transfer-Encryption: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)


-----BEGIN PGP MESSAGE-----
Version: ProtonMail
Comment: https://protonmail.com

wcBMA+mpixZUVs+xAQf/Zcyl0OkJuBskSQiEuJtzMYR9TWwkOsJnJrdUThgq
qNKskBSwpOORau78g+Gb1rEyao80MOCuMlzypAuax/f2UxPdJE4NvGYgq2y9
3O9DB1KemCSkR0edzrQucyEFd+KICcK+ibLhQ2WOLJK+ZQ2CeFVk0eQ9JeKv
vCngMKEUsAecot4oItx0EmZSLVPeuThV3iWXZWSqCEf5hsL/N4HRTUzM+lX6
ksTQIPcLrJC2G3ctkifIFWUzSkBOi936VNGgE7afAsORLn9jeRaivAN3pnKA
WcGH6t5jxRM3hPhXE/6hZdmAjcCxHSsWM6z2zkaPLvcIrKuoomKTsQdgfcR+
5tJTAdO2L9t+LwrTYPDr9Aagq0YoLkElIoqsME10Ss+7lC/eY5c6ZjCsjb6L
YEPHIAPhNOB+g+icCQObZwgIjiX+eA4FJHJgIxpT91IEyw8ETW+uNaQ=
=2K3x
-----END PGP MESSAGE-----
```

**Comment by niftylettuce** [comment] 2018-04-29 12:03
If you're sending to yourself Gmail will probably mark as spam.  Send from an outside email and let me know?

I also just got us whitelisted (temporarily until further review) by Barracuda.

**Comment by niftylettuce** [comment] 2018-04-30 11:49
Just to recap because I'm going to close this for now - if you send an email from your forwarded email to yourself, it will get marked as suspicious (this is expected behavior by Gmail).  For example you have a Gmail account foo@gmail.com, and you have forwarding setup so that any email to foo@beep.com will get forwarded to foo@gmail.com... AND you send an email in Gmail (logged in as foo@gmail.com) to foo@beep.com.  This email will 100% get marked as suspicious/spam by Gmail.  There are zero workarounds as far I know.

However if you send an email from an outside account, like beep@gmail.com to foo@beep.com, it will get forwarded just fine to foo@gmail.com.

**Closed by niftylettuce** 2018-04-30 11:49 UTC

**Comment by niftylettuce** [comment] 2018-10-30 22:54
@aliblackwell 	@bradlosh 	can you guys try the service again? I implemented and deployed a ton of core fixes and improved DMARC/DKIM/SPF deliverability.

**Comment by ProgrammerBruce** [comment] 2019-02-18 22:59
My setup and header results are similar to what @aliblackwell reported on 2018-04-09.  I get SPF failures for these two scenarios:

1. From a Gmail account, I send to a domain that is setup to forward with forwardemail.net to another domain I've hosted with ProtonMail, and ProtonMail reports that dmarc=fail, spf=fail, and dkim=pass.

Headers:
Return-Path: <FROM_ADDRESS_REMOVED@gmail.com>
X-Original-To: bruce@RECEIVING_DOMAIN_REMOVED.com
Delivered-To: bruce@RECEIVING_DOMAIN_REMOVED.com
Received: from mx1 (mx1.forwardemail.net [178.128.149.101]) (using TLSv1.2 with cipher
 ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)) (No client certificate requested) by
 mail17i.protonmail.ch (Postfix) with ESMTPS id E55C3300009B for
 <bruce@RECEIVING_DOMAIN_REMOVED.com>; Mon, 18 Feb 2019 18:56:09 +0000 (UTC)
Received: by mail-qt1-f182.google.com with SMTP id p48so20380226qtk.2 for
 <Bruce@FORWARDED_DOMAIN_REMOVED.email>; Mon, 18 Feb 2019 10:56:02 -0800 (PST)
Authentication-Results: mail17i.protonmail.ch; dmarc=fail (p=none dis=none)
 header.from=gmail.com
Authentication-Results: mail17i.protonmail.ch; spf=fail
 smtp.mailfrom=FROM_ADDRESS_REMOVED@gmail.com
Authentication-Results: mail17i.protonmail.ch; dkim=pass (1024-bit key)
 header.d=forwardemail.net header.i=@forwardemail.net header.b="od7byYhe"
Dkim-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=forwardemail.net; q=dns/txt;
 s=default; bh=DhgcN+ZRvFjX1S6YC7PNUcBG0wS6D/nbF+FI3QoIIRQ=;
 h=from:subject:date:message-id:to:mime-version:content-type:in-reply-to:references;
 b=od7byYhealsqQAuvc89ULhQeDEjIE/Hn411wV/mmU6yf55Ctf8Ek1C09TxhFI0uKhN/Nzpe+4
 dIuPm7PJHb5GKGaQrmX045DBDhJlwDQ6UfqB+5no2lTM+FsqYmJFOmrWVYXo0fxFRp+mS9SUJ16
 YlKCc8fJnbYmHmJmIVT973Q=

2. From a domain hosted with mailbox.org, I send to a domain that is setup to forward with forwardemail.net to another domain I've hosted with ProtonMail, and ProtonMail reports that dmarc=none, spf=fail, and dkim=pass.

Return-Path: <bruce@FROM_DOMAIN_REMOVED.com>
X-Original-To: bruce@RECEIVING_DOMAIN_REMOVED.com
Delivered-To: bruce@RECEIVING_DOMAIN_REMOVED.com
Received: from mx1 (mx1.forwardemail.net [178.128.149.101]) (using TLSv1.2 with cipher
 ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)) (No client certificate requested) by
 mail17i.protonmail.ch (Postfix) with ESMTPS id 5E2A83000098 for
 <bruce@RECEIVING_DOMAIN_REMOVED.com>; Mon, 18 Feb 2019 19:27:33 +0000 (UTC)
Authentication-Results: mail17i.protonmail.ch; dmarc=none (p=none dis=none)
 header.from=FROM_DOMAIN_REMOVED.COM
Authentication-Results: mail17i.protonmail.ch; spf=fail
 smtp.mailfrom=bruce@FROM_DOMAIN_REMOVED.com
Authentication-Results: mail17i.protonmail.ch; dkim=pass (1024-bit key)
 header.d=forwardemail.net header.i=@forwardemail.net header.b="BWMi46jP"
Dkim-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=forwardemail.net; q=dns/txt;
 s=default; bh=oQ2XnffOEdMStjrZOJUtCS+o9jYeTN2xbwWTboL3jjs=;
 h=from:subject:date:message-id:to:mime-version:content-type;
 b=BWMi46jPwh9hFEEZMISk0ko1lLJlfDNm77IzBToEGdgrLX8TuinMbvM0/JYoNeVFjqj+UMoj9
 Cc++TQSK5lt2sHcoSSUc06KaIvj8nJbvjPYfK5R3zIpds+bD3T7C/q1LRoonIh9YpBlfyDOKfbv
 jMN3sT31k4GwPcA1Gz4okOI=

Note that when sending from a Gmail account to the forwarded address, the header has two Received entries, but when sending from the mailbox.org hosted account, there is only one Received entry in the header.

**Comment by niftylettuce** [comment] 2019-03-12 10:18
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
