### ISSUE TITLE
Multiple emails missing Reply-To

### ISSUE THREAD

**Issue by justJS** [niftylettuce/forward-email#102] opened 2019-02-27 05:19 UTC
I've received multiple forwarded emails that are completely missing a Reply-To header (and I've thoroughly checked the entire headers I've received).

It seems to happen mainly when emails are sent from Proton Mail?

Here are the entire emails from one of these examples:

(is there any way to get the from email address? I'd really like to reply to this email)

```Feedback-Id: ⁨gXn07Q45w9AsxQUCS_MdPDVTFIhIVet-NOLxgfSogZDLzhFUq5Iuyi5tiKibLypwIvvsWVxjanmWMiUbBj8NFw==:Ext:ProtonMail⁩
Original-Recipient: ⁨rfc822;me@icloud.com⁩
X-Spam-Checker-Version: ⁨SpamAssassin 3.4.2 (2018-09-13) on mail.protonmail.ch⁩
Return-Path: ⁨<no-reply@forwardemail.net>⁩
X-Proofpoint-Virus-Version: ⁨vendor=fsecure engine=2.50.10434:,, definitions=2019-02-27_04:,, signatures=0⁩
Mime-Version: ⁨1.0⁩
Authentication-Results: ⁨ms11p00im-qufv10093101.me.com; dmarc=pass header.from=forwardemail.net⁩
Authentication-Results: ⁨ms11p00im-qufv10073101.me.com;	dkim=pass (1024-bit key) header.d=forwardemail.net header.i=@forwardemail.net header.b=OYxdlQdr⁩
Authentication-Results: ⁨ms11p00im-qufv10104001.me.com; spf=pass (ms11p00im-qufv10104001.me.com: domain of no-reply@forwardemail.net designates 178.128.149.101 as permitted sender) smtp.mailfrom=no-reply@forwardemail.net⁩
X-Mantsh: ⁨1TEIXR1kbG1oaGkNHB1tfTFwbGhsbGBoaGxEKTEMXGxoEGxsYBBsbGgQeGRAbHho fGhEKTFkXGxoaHxEKWU0Xbk9GQ1xPWBEKX1kXGBEKX00XZEVETxEKWUkXGnEaEBp3BgcbEnEbE hAYEncGGBoGGhEKWV4XbGx5EQpDThd7bU0SWx1EX1BmU3laUB4cXRlFbB9fZBN7TVkSZ1JnWxE KWFwXGQQaBB4aB0wbT0kSEhhIBRsaBBMEGwQdHxAbHhofGhEKXlkXflsSaBwRCk1cFxsfGhEKT FoXeG5DTWsRCkVZF01rEQpMXxd6BQUFBQUFBQUFGBEKTU4XbxEKQ1oXGx0SBBsYEgQbHhMEGxo bEQpCXBcbEQpeThcbEQpCSxdufFt/Tl9AaExHUBEKQkkXbnxbf05fQGhMR1ARCkJFF21aT0Adb X9Sc09jEQpCThdufFt/Tl9AaExHUBEKQkwXbVpPQB1tf1JzT2MRCkJsF21aT0AdbX9Sc09jEQp CQBdlSUdGHGl5cBxEWBEKQlgXYEh+YXBHb21jXRIRCk1eFxsRCnBoF2hgTmhrU0x/T0YZEBkaE QpwaBduEkNgHkVIHl5eYBAZGhEKcGgXek9cGUtfQHNnZBoQGRoRCnBoF25hbVwebXMeaRt4EBk aEQpwaBdnX3pofWFFAUJhRRAZGhEKbX4XGxEKWE0XSxE=⁩
X-Proofpoint-Spam-Details: ⁨rule=notspam policy=default score=0 spamscore=0 clxscore=1005 suspectscore=0 malwarescore=0 phishscore=0 adultscore=0 bulkscore=0 classifier=clx:Deliver adjust=0 reason=mlx scancount=1 engine=8.0.1-1812120000 definitions=main-1902270036⁩
X-Clx-Score: ⁨1005⁩
X-Clx-Shades: ⁨Deliver⁩
X-Clx-Ushades: ⁨None⁩
Dkim-Signature: ⁨v=1; a=rsa-sha256; c=relaxed/relaxed; d=forwardemail.net; q=dns/txt; s=default; bh=m2F3Qd6f97/+xZwAPqGx+28GIfmumpvNPxMykhfvkl0=; h=from:subject:date:message-id:to:mime-version:content-type; b=OYxdlQdr4LNlwC+tLdJlDDnMcMfS1hoo9p/bJYSpyo1hhroo2c+ry5YATqdJ+UdEiYXV4P85V 4rcsS5Xe8XCy2/WVu9BigXh9BsNm4JKfYHtHa/HVi/3N98/nARn2LwEojZz6jjdXQhURY792XV9 E+/Vsai97b54sRurPIW9j1Y=⁩
⁨<rTvVU7GVFspNChdQtr-4Li2bNqeJVi3dDib2slLsg1zBrhaznDSK3rXd1h4t5dQB5zMcnnmqEwhL-N1EEk5CQ0Yb9e1tZDHubDov1Qu6JCM=@protonmail.ch>⁩
X-Clx-Unspecialscore: ⁨2⁩
X-Clx-Spam: ⁨false⁩
X-Spam-Status: ⁨No, score=-1.2 required=7.0 tests=ALL_TRUSTED,DKIM_SIGNED, DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,FREEMAIL_FROM,HTML_MESSAGE autolearn=ham autolearn_force=no version=3.4.2⁩
Content-Type: ⁨multipart/alternative; boundary=--_NmP-a990b892f0b4f8d1-Part_1⁩
X-Dmarc-Info: ⁨pass=pass; dmarc-policy=reject; s=r1; d=r1⁩
X-Dmarc-Policy: ⁨v=DMARC1; p=reject; pct=100; rua=mailto:re+nvwscv8cppr@dmarc.postmarkapp.com; sp=none; aspf=r;⁩
Received-Spf: ⁨pass (ms11p00im-qufv10104001.me.com: domain of no-reply@forwardemail.net designates 178.128.149.101 as permitted sender) receiver=ms11p00im-qufv10104001.me.com; client-ip=178.128.149.101; helo=mx1; envelope-from=no-reply@forwardemail.net⁩
Received: ⁨from ms11p00im-qufv17081101.me.com ([17.58.36.53]) by ms26521.mac.com (Oracle Communications Messaging Server 8.0.1.3.20170906 64bit (built Sep  6 2017)) with ESMTP id <0PNK00JIJJQ7WUC0@ms26521.mac.com> for me@icloud.com; Wed, 27 Feb 2019 05:10:55 +0000 (GMT)⁩
Received: ⁨from mx1 (mx1.forwardemail.net [178.128.149.101]) by ms11p00im-qufv17081101.me.com (Postfix) with ESMTPS id CEAC910005E	for <me@icloud.com>; Wed, 27 Feb 2019 05:10:54 +0000 (UTC)⁩```

**Comment by astrob0t** [comment] 2019-02-27 05:38
Possible duplicate of #96

**Comment by niftylettuce** [comment] 2019-02-27 06:10
Sorry I had to take time away from open source, I hope to be able to dedicate more time this weekend.

**Comment by niftylettuce** [comment] 2019-03-12 10:23
Can you please try again?  Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.

**Closed by niftylettuce** 2019-03-12 10:23 UTC

**Comment by justJS** [comment] 2019-03-12 10:25
Thanks for the update @niftylettuce. I haven't been experiencing this issue recently but I'll make sure to let you know if it happens again 👍
